fix #70 stake out
MerginMaps/docs pull request #121
Opened 2022-03-07 00:23 UTC by alex-cit

wip #70 
I need to redo the screenshots, so that they show the same features (something nicer than feature X) and reasonable GPS accuracy.

2022-03-07 07:52 UTC, PeterPetrik commented
@tomasMizera can you look too please?

2022-03-09 13:57 UTC, tomasMizera requested changes
It looks great, thanks! I left two minor notes, I am not sure if we want to add precise distances or not. I will leave the decision with you guys.

I am only worried about one thing. I saw in the included pictures that the short navigation mode is not rendered properly (outer circle is cut on top and bottom):

<img src="https://user-images.githubusercontent.com/22449698/157454925-9eb72707-4253-4ea2-aeef-b8a9ff1caed7.png" width=300>

@alex-cit If you are using landscape mode, can you please try it in portrait mode and take picture with nicely rendered circles? (note: https://github.com/lutraconsulting/input/issues/1948) If you are not able to get that, I can help you out with it, let me know :)

2022-03-09 13:57 UTC, tomasMizera commented on src/field/stake-out/index.md
> +3. Once you are closer to the point, the stake out panel will switch to short navigation mode.
Short mode is visible if user is less than 1m from destination point, but I am not sure if we want to mention that.

2022-03-09 13:57 UTC, tomasMizera commented on src/field/stake-out/index.md
> +4. Precise stake out of the point is highlighted by green:
It gets green when user is less than 10cm from target, but again, I am not sure if we want to mention that.

2022-03-13 18:48 UTC, alex-cit commented
Screenshots will be updated later - https://github.com/MerginMaps/docs/issues/126

2022-03-14 07:09 UTC, merged