DR dashboard
MerginMaps/docs pull request #441
Opened 2024-03-15 21:36 UTC by alex-cit

related to #436 
Dashboard Redesign - screenshots update https://merginmaps.com/docs/manage/dashboard/

2024-03-21 08:24 UTC, MarcelGeo requested changes

2024-03-21 08:24 UTC, MarcelGeo commented on src/manage/dashboard/mergin-maps-dashboard.jpg
@alex-cit - could you please use wider screen for his screenshot? I want to see similar padding around sections as in e.g. src/manage/dashboard/mergin-maps-project-details.jpg . Thanks :)

2024-03-21 08:42 UTC, MarcelGeo requested changes

2024-03-21 08:42 UTC, MarcelGeo commented on src/manage/dashboard/mergin-maps-dashboard-project-history-version.jpg
@alex-cit  - could you please use screenshot without "v3" small title in header? We fixed that already - it's not showing after short scroll.

2024-03-21 16:54 UTC, alex-cit commented
Fixed, thanks for the review!

2024-03-22 07:50 UTC, MarcelGeo approved these changes

2024-03-22 16:14 UTC, raherin requested changes

2024-03-22 16:14 UTC, raherin commented on src/manage/dashboard/index.md
>  Current workspace and your username are displayed in the upper right corner of the screen.
Edit text:
The current workspace and your username are displayed in the upper right corner of the screen.

2024-03-22 16:14 UTC, raherin commented on src/manage/dashboard/index.md
> +- search project by name
Edit text:
- search for a project by name

2024-03-22 16:14 UTC, raherin commented on src/manage/dashboard/index.md
> +**Webmap** feature is available for [Team subscription](https://merginmaps.com/pricing).
Edit text:
The **Webmap** feature is available for `[Team subscription](https://merginmaps.com/pricing).`

2024-03-22 16:14 UTC, raherin commented on src/manage/dashboard/index.md
> +**History** contains the overview of available project versions that can be also downloaded to your computer.
Edit text:
The **History** tab contains an overview of available project versions that can be also downloaded to your computer.

2024-03-22 16:14 UTC, raherin commented on src/manage/dashboard/index.md
> +Click on **Manage subscription** to visit the subscription management portal where you can update the subscription plan, billing information, see invoices and upcoming payments.
Edit text:
Click on **Manage subscription** to visit the subscription management portal where you can update the subscription plan, billing information, and see invoices and upcoming payments.

2024-03-26 07:08 UTC, merged