DR troubleshoot - sharing project with mergin maps support
MerginMaps/docs pull request #442
Opened 2024-03-15 22:10 UTC by alex-cit

related to  #436 
Dashboard Redesign - screenshots update -  https://merginmaps.com/docs/misc/troubleshoot/

2024-03-21 11:24 UTC, MarcelGeo approved these changes

2024-03-22 15:59 UTC, raherin requested changes

2024-03-22 15:59 UTC, raherin commented on src/misc/troubleshoot.md
>  To share your <MainPlatformName /> project with the support:
Edit text:
To share your <MainPlatformName /> project with the support team:

2024-03-22 15:59 UTC, raherin commented on src/misc/troubleshoot.md
> +2. In the **Project** tab in the left panel, find the project that needs to be shared with the support and click on it.
Edit text:
In the **Project** tab on the left panel, find the project that needs to be shared with the support team and click on it.

2024-03-22 15:59 UTC, raherin commented on src/misc/troubleshoot.md
> +4. Use the email <MerginMapsEmail id="support" /> in the sharing form and click **Share** to send the invitation to the support.
Edit text:
Use the email `<MerginMapsEmail id="support" />` in the sharing form and click **Share** to send the invitation to the support team.

2024-03-22 15:59 UTC, raherin commented on src/misc/troubleshoot.md
> +   ![Sharing Mergin Maps project with the support](./mergin-maps-share-project-with-support.jpg "Sharing Mergin Maps project with the support")
Edit image text:
`![Sharing Mergin Maps project with the support team](./mergin-maps-share-project-with-support.jpg "Sharing Mergin Maps project with the support team")`

2024-03-26 06:43 UTC, merged