DR How to update files
MerginMaps/docs pull request #443
Opened 2024-03-16 06:48 UTC by alex-cit

related to #436 
Dashboard Redesign - screenshots update - https://merginmaps.com/docs/manage/delete-files/

2024-03-21 11:14 UTC, MarcelGeo approved these changes

2024-03-22 15:55 UTC, raherin requested changes

2024-03-22 15:55 UTC, raherin commented on src/manage/delete-files/index.md
> +Deleting files through <MainDomainName /> is simple. However, you can only delete one file at the time.
Edit text:
Deleting files through `<MainDomainName />` is simple. However, you can only delete one file at a time.

2024-03-22 15:55 UTC, raherin commented on src/manage/delete-files/index.md
> +1. Log in <AppDomainNameLink /> and navigate to your project.
Edit text:
Log in to `<AppDomainNameLink />` and navigate to your project.

2024-03-26 06:43 UTC, merged