DR dashboard - create new project
MerginMaps/docs pull request #444
Opened 2024-03-16 07:49 UTC by alex-cit

related to #436 
Dashboard Redesign - screenshots update -  https://merginmaps.com/docs/manage/create-project/#create-a-project-through-merginmaps-com

2024-03-21 09:47 UTC, MarcelGeo commented on src/manage/create-project/index.md
>  ## Create a project through merginmaps.com
merginmaps.com -> dashboard ?

2024-03-21 09:51 UTC, MarcelGeo approved these changes

2024-03-22 15:50 UTC, raherin requested changes

2024-03-22 15:50 UTC, raherin commented on src/manage/create-project/index.md
> +## Create a project through Mergin Maps dashboard
Edit text:
Create a project through the Mergin Maps dashboard

2024-03-22 15:50 UTC, raherin commented on src/manage/create-project/index.md
> +### Clone an existing project through Mergin Maps dashboard
Edit text:
Clone an existing project through the Mergin Maps dashboard

2024-03-22 15:50 UTC, raherin commented on src/manage/create-project/index.md
>  3. The project's page opens. Click on the **Clone** button to clone the project.
Edit text:
3. When the project's page opens, click on the **Clone** button to clone the project.

2024-03-22 15:50 UTC, raherin commented on src/manage/create-project/index.md
> +3. Now you can change the project's name and select the target workspace. Confirm by clicking **Clone project**.
Should this be step 4?

2024-03-26 06:43 UTC, merged