DR workspaces
MerginMaps/docs pull request #445
Opened 2024-03-17 14:15 UTC by alex-cit

related to #436 
Dashboard Redesign - screenshots update -  https://merginmaps.com/docs/manage/workspaces/

2024-03-21 08:53 UTC, MarcelGeo requested changes

2024-03-21 08:53 UTC, MarcelGeo commented on src/manage/workspaces/index.md
>  ### Switch workspaces in merginmaps.com
Could you rename merginmaps.com to "dashboard" ?

2024-03-21 16:53 UTC, alex-cit commented
Fixed, thanks for the review!

2024-03-22 07:47 UTC, MarcelGeo approved these changes

2024-03-22 15:41 UTC, raherin commented on src/manage/workspaces/index.md
> +Note that every workspace has its own subscription. When created, the workspace starts with the free trial. After the trial period, you will have to [switch to a paid subscription](../../manage/subsc
Edit text:
Note that every workspace has its own subscription. When created, the workspace starts with a free trial. After the trial period, you will have to [switch to a paid subscription](../../manage/subscriptions/#how-to-change-a-subscription). Currently, it is possible to have up to 3 workspaces without a subscription (using the trial) simultaneously.

2024-03-26 06:42 UTC, merged