DR tutorial working collaboratively
MerginMaps/docs pull request #446
Opened 2024-03-17 15:33 UTC by alex-cit

related to #436 
Dashboard Redesign - screenshots update -  https://merginmaps.com/docs/tutorials/working-collaboratively/

2024-03-21 11:12 UTC, MarcelGeo requested changes

2024-03-21 11:23 UTC, MarcelGeo requested changes

2024-03-21 11:23 UTC, MarcelGeo commented on src/tutorials/working-collaboratively/index.md
> +   You can enter multiple emails in the **Share with** field and invite multiple people at once.
You add also usernames into Share with

![image](https://github.com/MerginMaps/docs/assets/12643115/1113c868-45f7-46d0-9639-83ef2f629b6f)

2024-03-21 17:17 UTC, alex-cit commented on src/manage/project-advanced.md
> -3. In the invite form, enter the email addresses of people you want to invite.
good points, thanks!

2024-03-21 17:21 UTC, alex-cit commented
thanks for the review, it should be fixed now :)

2024-03-22 07:45 UTC, MarcelGeo approved these changes

2024-03-22 12:54 UTC, raherin commented on src/manage/project-advanced.md
> +   - If you want to invite them only to some projects, select the *Guest* option and specify which projects should be shared with them.
Edit text:
If you only want to invite them to some projects, select the *Guest* option and specify which projects should be shared with them.

2024-03-22 12:54 UTC, raherin commented on src/manage/project-advanced.md
> +1. Log in <AppDomainNameLink /> and navigate to the project you want to delete
Edit text:
Log in to `<AppDomainNameLink />`

2024-03-26 06:42 UTC, merged