DR project history
MerginMaps/docs pull request #447
Opened 2024-03-18 18:40 UTC by alex-cit

related to #436 
Dashboard Redesign - screenshots update -  https://merginmaps.com/docs/manage/project-details/

2024-03-21 11:16 UTC, MarcelGeo approved these changes

2024-03-22 12:44 UTC, raherin requested changes

2024-03-22 12:44 UTC, raherin commented on src/manage/project-details.md
> +3. Click on a version to see the more details about what was changed.
Change text to:
Click on a version to see more details about what was changed.

2024-03-22 12:44 UTC, raherin commented on src/manage/project-details.md
> +   Here, there are multiple changes in the `trees` layer. One feature (`fid: 9`) was added, one feature (`fid: 6`) was deleted. There are two modified features: `fid: 2` was moved to a new position a
Edit last sentence to be a list:
There are two modified features: 
- `fid: 2` was moved to a new position 
- For `fid: 8`, the value of attribute `species` was changed

2024-03-26 06:41 UTC, merged