Map overviews (webmap)
MerginMaps/docs pull request #502
Opened 2024-09-15 16:16 UTC by alex-cit

wip #500
Map overviews (webmap) page added to the docs.

TODO:
- are the usage details correct?
- more troubleshooting tips?

2024-09-16 08:32 UTC, MarcelGeo requested changes

2024-09-16 08:32 UTC, MarcelGeo commented on src/.vuepress/sidebar/en.js
> +                '/manage/webmap/',
Add map 'map-overviews'

2024-09-16 08:32 UTC, MarcelGeo commented on src/manage/webmap/index.md
> +Map Overviews can be used with *Team*, *Academia* and *Non-profit* <MainDomainNameLink id="pricing" desc="subscription plans"/>, as well as in [<CommunityPlatformName />](../../server/) and [<Enterpr
Map overviews are not available in CE and EE now :)

2024-09-16 08:32 UTC, MarcelGeo commented on src/manage/webmap/index.md
> +The content of the map overview as well as the **Layers** panel are refreshed after every update. This means that you should always see here your current spatial data.
every push to project / synchronization

2024-09-16 08:32 UTC, MarcelGeo commented on src/manage/webmap/index.md
> +In the map overview, you will see your survey layers or raster layers that are [packaged](../project/#packaging-qgis-project) with the project. Other layers, such as online [background maps](../../gi
Yeah... postgres and any other network layers are not available.

2024-09-16 08:32 UTC, MarcelGeo commented on src/manage/webmap/index.md
> +The extent of map overviews is defined by the [extent set in the QGIS project](../../gis/features/#project-extent) and the extent of the data that are included in the current version of the project.
Under the hood ... there is no combination of extent defined in project and data. If the project extent is not defined, we are trying to get extent from advertised extent:

![image](https://github.com/user-attachments/assets/070b1a8a-1abd-4254-b054-fe7c3cf2ecbd)

If there is not, layers extents are calculating. This should go to troubleshooting probably :)

2024-09-19 08:45 UTC, MarcelGeo approved these changes

2024-09-27 13:25 UTC, tomasMizera approved these changes
It looks all good, thanks for compiling this @alex-cit @MarcelGeo!
I think this is a good starting point, for future we could also add a section about which layers are kept and which are filtered away (the remote ones).

There is just one minor comment from me. Once edited, we can merge 🎉

2024-09-27 13:25 UTC, tomasMizera commented on src/manage/dashboard-maps/index.md
> +This usually happens when the map was not initiated. All you need to do is to update the project: the map is refreshed after every synchronisation, so your update will activate the map content.
Not sure if people know what it means to "update the project" - how about saying that they need to create a new version or synchronize some change?

2024-10-01 09:07 UTC, tomasMizera commented
Thanks, let's merge this one :)

2024-10-01 09:07 UTC, merged