Extent for  maps in dashboard
MerginMaps/docs pull request #531
Opened 2024-12-01 15:35 UTC by alex-cit

#514  Added info about how the extent is defined for maps in dashboard.

2024-12-02 08:35 UTC, tomasMizera commented
LGTM, @MarcelGeo can you please double-check if the logic is like this?

2024-12-11 09:47 UTC, MarcelGeo commented
@tomasMizera @alex-cit 1. is extent from view settings 2. is extent from qgis server settings ... reorder it in text.

We wanted to update this order, but it's not done yet and I think we can update it in future.

2024-12-11 09:53 UTC, MarcelGeo requested changes

2024-12-11 09:53 UTC, MarcelGeo commented on src/manage/dashboard-maps/index.md
> +When displaying maps in <DashboardShortLink />, <MainPlatformName /> uses primarily the *Advertised extent* defined in **QGIS Server** tab.
Primarly is used View settings extent

2024-12-16 14:50 UTC, MarcelGeo approved these changes

2024-12-16 14:50 UTC, merged